package rules

import com.example.SmartHouseAPI.model.FailedLogin;
import com.example.SmartHouseAPI.model.LoginViolation;
import java.util.List;


rule "Three Failed Logins"
when
    $failedLoginOne: FailedLogin($email: email)
    $failedLoginTwo: FailedLogin(email == $email, this != $failedLoginOne)
    $failedLoginThree: FailedLogin(email == $email, this != $failedLoginOne, this != $failedLoginTwo)
    not LoginViolation(email == $email)
then
    insert(new LoginViolation($email));
end
